### PR TITLE
#UX-412 ResultItem for logs, tests

### PR DESCRIPTION
**Pull request by sophistifunk**
UX-412 Developer sees the log broken down by step -- ResultItem component

 * Add ResultItem component, styles, storybook
 * Some tangentially related fixes
 * Fix Flow errors
 * Switch gulp watch and watch-styles to not run tests or eslint

### CODE REVIEW

**Comment by sophistifunk** [comment]
Not sure what's wrong with FSEvents, but I've been getting a lot of angry reports from V8 about stuff soon to be removed that's probably related :-/

**Comment by michaelneale** [comment]
@sophistifunk not sure why but a failure running the build: 

sh: 1: node-pre-gyp: not found
npm info lifecycle fsevents@1.0.11~install: Failed to exec install script

could be environmental

**Comment by michaelneale** [comment]
@sophistifunk if you think it is a node version thing: https://hub.docker.com/_/node/ has the versions available, Putting those version tags at the top of the Dockerfile and updating this PR will cause the build to run with that version of node available.

**Comment by i386** [comment]
So glad to see this landing 🎉👌

**Comment by sophistifunk** [comment]
@i386 you and me both 😆

**Comment by michaelneale** [comment]
@i386 sadly when I see spurious failures of npm I see days ahead of yak shaving :(

**Comment by michaelneale** [comment]
OK looking good. 

@sophistifunk sorry I had to muck with this, let me explain: 

1) can't invoke "npm run gulp" right now - as paths have "%" in them (due to naming of pull request). known problem with npm (Jenkins will soon fix to not use things like that in paths)
2) it seems on linux this build is not stable with node 6, so I set the version in the Dockerfile to 5.11.1, which seems to make it reliable.

**Pull request merged**
