### PR TITLE
[FIX JENKINS-36660] hooks for AT

### PR DESCRIPTION
**Pull request by scherler**
**Description**

This small change helps to match the nav tabs in AT, otherwise we need to match against URL which is more complicated in folder/multibranch projects

**Submitter checklist**
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests

**Reviewer checklist**
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@reviewbybees

### CODE REVIEW

**Comment by michaelneale** [comment]
seems good to me - @tfennelly ?

**Comment by scherler** [comment]
BLOCKS 

- jenkinsci/blueocean-acceptance-test#26

- https://github.com/jenkinsci/blueocean-plugin/pull/433

**Comment by tfennelly** [comment]
🐝 insofar as I get them.

So ... would adding a class on an element in the page not help here and be easier to use ... seems like using URLs is going to be brittle, no?

**Comment by scherler** [comment]
That is the change, we are using now a class and not the URL anymore, since building url in a sane way for multibranch in folder in AT is no fun only to match some tab

**Comment by tfennelly** [comment]
@scherler duh .... now I see it ... sorry. Thanks.

**Comment by tfennelly** [comment]
🐝  again , just in case there was a doubt.

**Comment by kzantow** [comment]
:bee:

**Pull request merged**
