### PR TITLE
experiment/enzyme karma - using karma test runner for JDL

### PR DESCRIPTION
**Pull request by cliffmeyers**
An experiment to add Karma test runner to the JDL. This could supplant gulp-mocha if we decide we like it better but I left gulp-mocha in for now alongside Karma.

Benefits:
* Tests can be run in PhantomJS or any browser
* Easy to debug tests in browser
* Built-in autowatch

Cons:
* Karma config takes a little work to sort out

@reviewbybees

### CODE REVIEW

**Comment by michaelneale** [comment]
Karma! I was trying to remember this ones name yesterday. I like it, @sophistifunk @tfennelly ??

**Comment by tfennelly** [comment]
🐝 anything that helps with testing ... looks great !!

Is there a test?

**Comment by cliffmeyers** [comment]
@tfennelly I added some additional tests in a related PR that was already merged. See this commit:  https://github.com/jenkinsci/jenkins-design-language/pull/35/commits/fc29f864adde837c6cd5c80bb4ce4f04636d542d

**Comment by tfennelly** [comment]
@cliffmeyers awesome ... merge it 👍

**Pull request merged**
