### PR TITLE
Add close button to dialog

### PR DESCRIPTION
**Pull request by kzantow**
**Description**
Add a standard close button to dialog:

image

**Submitter checklist**
- [x] Change is code complete

@i386 @sophistifunk @michaelneale  PTAL, not sure you want this but I think it makes sense to have a standard close button on dialogs, could be hidden by default, up to you...

### CODE REVIEW

**Comment by sophistifunk** [comment]
This will look great with our "giant close button used to indicate failure" feature. :-|

**Comment by kzantow** [comment]
@sophistifunk hahaha... ehh.... maybe there are some ideas to change the 'giant close button to indicate failure'

**Comment by i386** [comment]
@brody ping

**Comment by kzantow** [comment]
@brody WDYT about a standard close button like this?

**Comment by brody** [comment]
@kzantow The Primary button should be whatever the action is (eg Submit) and the secondary button should be "Close" or "Cancel". Hitting ESC or clicking outside the modal would also dismiss it.
Let me know if you can think of any edgecases where the above pattern wouldn't work.

image

**Pull request closed without merging**
