### PR TITLE
Jenkins 36770 JDL component for progress bars

### PR DESCRIPTION
**Pull request by scherler**
**Decription**

Adds component based on svg and css animation. Has determinate and indeterminate state.

https://youtu.be/SbpbPC9qmVg Sample from storyBook

Not sure how to test this, could look into some unit test, but not sure.

screenshot from 2016-07-29 19-05-04

**Submitter checklist**
- [x] Change is code complete and matches issue description
- [x] Apppropriate unit or acceptance tests or explaination to why this change has no tests

**Reviewer checklist**
- [x] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explaination given

@reviewbybees

### CODE REVIEW

**Comment by i386** [comment]
@scherler these look fantastic - nice one 💯

**Comment by sophistifunk** [comment]
Visually I think an empty bar for "indeterminate" is a bad choice, but the code looks good 🐝

**Comment by scherler** [comment]
@sophistifunk did you see the video?  That state has a 25% line which is animated

**Comment by scherler** [comment]
@sophistifunk did you see the video?  That state has a 25% line which is animated

**Pull request merged**
