### PR TITLE
[JENKINS-36209] Style changes for queued items

### PR DESCRIPTION
**Pull request by imeredith**
**Decription**

Style changes for https://github.com/jenkinsci/blueocean-plugin/pull/389

**Submitter checklist**
- [x] Change is code complete and matches issue description
- [x] Apppropriate unit or acceptance tests or explaination to why this change has no tests

**Reviewer checklist**
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explaination given

@reviewbybees 

* Updated styles for queued items.
* Moved Result.jsx into blueocean-dashbaord

### CODE REVIEW

**Comment by i386** [comment]
@imeredith can I get a screen grab please?

**Comment by michaelneale** [comment]
Flow failure: 

```
Logs will go to /tmp/flow/zShomezSubuntuzSslavezSworkspacezSjenkins-design-languagezSJENKINS-36209-queued-activity-items.log
Started a new flow server: \flow is still initializing; this can take some time. [parsing] |flow is still initializing; this can take some time. [parsing] /flow is still initializing; this can take some time. [local inference] -flow is still initializing; this can take some time. [local inference] \flow is still initializing; this can take some time. [merging inference] |src/js/components/index.js:22
 22: export {PipelineResult} from './pipeResult/Result';
                                  ^^^^^^^^^^^^^^^^^^^^^ ./pipeResult/Result. Required module not found
```

cc @imeredith

**Comment by imeredith** [comment]
image

**Comment by michaelneale** [comment]
:bee: looks good I think. So this is removing a component that shouldn't be there as well right?

**Comment by michaelneale** [comment]
@imeredith does this need ot be released as a beta and then used in the PR for blue ocean?

**Comment by i386** [comment]
@imeredith that indicator and message looks off 

result - queued

**Comment by imeredith** [comment]
Ah I'll fix that up, i couldnt find the original image.

**Comment by i386** [comment]
@imeredith thanks 👍

**Comment by imeredith** [comment]
image

@i386 better?

**Comment by i386** [comment]
Much better. Could you add about 15px spacing between the text and the icon?

**Comment by imeredith** [comment]
image

**Pull request merged**
