### PR TITLE
Jenkins-36065 icon alignment

### PR DESCRIPTION
**Pull request by sophistifunk**
* Update some dependencies to kill v8 warnings
* Slight tweak to alignment of status glyph in ResultItem

@reviewbybees

### CODE REVIEW

**Comment by sophistifunk** [comment]
screen shot 2016-06-22 at 12 46 28 pm

**Comment by i386** [comment]
Looks 👍 🐝

**Comment by michaelneale** [comment]
baws

**Comment by sophistifunk** [comment]
I'll publish this and update BO

**Pull request merged**
