### PR TITLE
Task/jenkins 37715 publish workflow

### PR DESCRIPTION
**Pull request by cliffmeyers**
**Description**
- This is more or less a replacement of #94 just with a slightly cleaner commit history. I've tested "npm run release" and "npm run release-beta" and they both work as expected (except for me site-publish fails because of some pub key config w/ github, but not really an issue with these changes).
- Added a script that performs a number of checks:
  - No ambiguous versions in deps or devDeps
  - No duplicates in devDeps that are already in deps
  - No deps in package.json that aren't in npm-shrinkwrap.json
- Also discovered that we probably need to stick with 2-space indent in package.json because any npm operation against that file (install --save/Dev, version, etc) will enforce that spacing and there's no sense fighting it. My bad for not realizing that sooner.
- See [JENKINS-37715](https://issues.jenkins-ci.org/browse/JENKINS-37715).

**Submitter checklist**
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests

**Reviewer checklist**
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@reviewbybees

### CODE REVIEW

**Comment by cliffmeyers** [comment]
cc @tfennelly @sophistifunk

**Comment by tfennelly** [comment]
🐝 LGTM

**Comment by tfennelly** [comment]
The likes of https://www.npmjs.com/package/release-it also look intersting

**Comment by cliffmeyers** [comment]
I'm going to put this PR on-hold. I think @tfennelly 's suggestion of release-it may be a better long-term solution for us.

**Pull request closed without merging**
