### PR TITLE
[JENKINS-36906] add "small" button style

### PR DESCRIPTION
**Pull request by cliffmeyers**
**Description**

**Submitter checklist**
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests

**Reviewer checklist**
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@reviewbybees

### CODE REVIEW

**Comment by cliffmeyers** [comment]
Needs a few more refinements before ready for review.

**Comment by i386** [comment]
@cliffmeyers can you post a screen grab here?

**Comment by cliffmeyers** [comment]
screen shot 2016-09-07 at 11 26 48 am

**Comment by i386** [comment]
Looks good! Need some 🐝 before merging

**Comment by imeredith** [comment]
:bee: from me

**Pull request merged**
