### PR TITLE
make log view better

### PR DESCRIPTION
**Pull request by helloyou2012**
**Description**

Some of log tables alignment with space, `pre-wrap` make it shows better.

### CODE REVIEW

**Comment by i386** [comment]
Thanks @helloyou2012 

@scherler could you PTAL?

**Comment by michaelneale** [comment]
ping @i386 @scherler

**Comment by i386** [comment]
@michaelneale not sure what the effect is - will rely on @scherler to tell me :)

**Comment by scherler** [comment]
@helloyou2012 @i386 @michaelneale the notification for this must have been gone down the spam folder. Sorry about it. Will have a look now.

**Comment by scherler** [comment]
@helloyou2012 I do not see any difference, what so ever. Can you provide a before and after screen shot?

screenshot from 2016-09-27 15-09-10
screenshot from 2016-09-27 15-08-47

**Comment by helloyou2012** [comment]
Before:

image

After:

image

**Comment by i386** [comment]
Oh I see. Nice one 👍

**Comment by michaelneale** [comment]
NICE
👍 👍 👍 👍 👍 👍 👍 👍

**Comment by michaelneale** [comment]
@scherler @sophistifunk can we get this in some time?

**Comment by sophistifunk** [comment]
This seems pretty clearly a win to me 🐝

**Comment by i386** [comment]
This is a really great change 🍾

**Pull request merged**
