### PR TITLE
[JENKINS-35768] support arbitrary content in Table headers

### PR DESCRIPTION
**Pull request by cliffmeyers**
**Description**
- The JIRA ticket linked below requires arbitrary React / HTML content inside of a table header cell. This was the least invasive change to accomplish it.
- See [JENKINS-35768](https://issues.jenkins-ci.org/browse/JENKINS-35768).

**Submitter checklist**
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests

**Reviewer checklist**
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@reviewbybees

### CODE REVIEW

**Comment by cliffmeyers** [comment]
As usual feedback (especially from @sophistifunk) is welcome.

**Comment by michaelneale** [comment]
:bee:

**Comment by cliffmeyers** [comment]
As this is a requirement only for branch filtering, I am deferring merge on this until it's time to pick that work up again.

**Comment by kzantow** [comment]
@cliffmeyers FYI, I implemented branch filtering already without this, though this could be useful I suppose.

**Comment by cliffmeyers** [comment]
I think @sophistifunk is going to rework the tables anyways so I'm guessing this PR will be closed. It would probably be good if that new component supports arbitrary React elements in the header?

**Comment by kzantow** [comment]
@cliffmeyers yes, probably just dump whatever header in directly to the page to support strings or components

**Comment by cliffmeyers** [comment]
Closing this as it's been obviated by the new table component in #155

**Pull request closed without merging**
