### PR TITLE
Task/arbitrary table props

### PR DESCRIPTION
**Pull request by sophistifunk**
**Description**

Forward arbitrary props in table components, mainly to support `data-X` attribs, but also for `title` etc.

@reviewbybees

### CODE REVIEW

**Comment by sophistifunk** [comment]
*ping* @cliffmeyers @kzantow if you've got a minute.

**Comment by cliffmeyers** [comment]
I'm sure this change is probably fine, could you just explain how `restProps` is getting defined? Is using `... someVar` at the end of the destructuring assignment taking all the other props from `this.props` except those explicitly defined beforehand?

**Comment by sophistifunk** [comment]
Yeah, it's super-useful for this sort of thing.

**Comment by michaelneale** [comment]
:bee: I guess. data tags are most useful.

**Pull request merged**
