### PR TITLE
[FIX JENKINS-38493_Add_a_new_status_indicator_for_waiting_for_input]

### PR DESCRIPTION
**Pull request by scherler**
**Description**
- See [JENKINS-38493](https://issues.jenkins-ci.org/browse/JENKINS-38493).

Implemented in statusIndicatorStories.jsx
screenshot from 2016-12-14 16-37-05

and resultItemStories.jsx
screenshot from 2016-12-14 16-36-45

Snapshot: `@jenkins-cd/design-language@0.0.92-unpublishedPaused`

**Submitter checklist**
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests

**Reviewer checklist**
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@reviewbybees

…t pause icon/state as jdl component and in story book

### CODE REVIEW

**Comment by michaelneale** [comment]
nice work thor! 

:bee:

**Comment by i386** [comment]
NIIICE

**Comment by michaelneale** [comment]
CAN SPACEFLIGHTS BE STOPPED??

**Comment by scherler** [comment]
:) thanks @i386 @michaelneale

**Comment by scherler** [comment]
@michaelneale @i386 actually that is part JENKINS-38493 Add a new status indicator for "waiting for input"

**Comment by i386** [comment]
@scherler yep and better than seeing the "purple vomit question mark" ;)

**Comment by scherler** [comment]
@jenkins-cd/design-language@0.0.92 published

**Pull request merged**
