### PR TITLE
Bug/jenkins 39057 text misaligned ie11

### PR DESCRIPTION
**Pull request by cliffmeyers**
**Description**
- See [JENKINS-39057](https://issues.jenkins-ci.org/browse/JENKINS-39057).

**Submitter checklist**
- [x] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests

**Reviewer checklist**
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@reviewbybees

### CODE REVIEW

**Comment by cliffmeyers** [comment]
Pending discussion with @brody

**Comment by cliffmeyers** [comment]
On hold pending response from Lato font team.

**Comment by i386** [comment]
@cliffmeyers could you forward me the email you sent?

**Comment by michaelneale** [comment]
any progress on this hilarious issue? It's just so much fun.

**Comment by cliffmeyers** [comment]
I never heard anything back from the Lato team. IMO we should just use a generic sans-serif font for IE11 and call it a day.  @brody ?

**Pull request closed without merging**
