### PR TITLE
Fix flow 2016-07-04

### PR DESCRIPTION
**Pull request by sophistifunk**
* Fix up current flow errors
* Add flow to Jenkinsfile

### CODE REVIEW

**Comment by sophistifunk** [comment]
Hrm. Mystery failure, but definitely to do with flow.

**Comment by michaelneale** [comment]
related to https://github.com/facebook/flow/issues/210 likely

**Comment by michaelneale** [comment]
yes adding that dep in helped.

**Comment by sophistifunk** [comment]
Wait, didn't this work yesterday?

manhattan

**Comment by michaelneale** [comment]
@sophistifunk yes, as you can see from status is all good.

**Comment by michaelneale** [comment]
:bee: even I  can understand the types, and Jenkinsfile change looks reasonable.

**Comment by sophistifunk** [comment]
Suckers!

/me deploys to PROD and goes on safari for 6 months

**Pull request merged**
