### PR TITLE
Fix styling issue with code block

### PR DESCRIPTION
**Pull request by EcutDavid**
**Description**
From
image
To
image

Didn't find tickets for this repo in JIRA site, that's why no ticket linked.

**Submitter checklist**
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests

**Reviewer checklist**
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@reviewbybees

### CODE REVIEW

**Comment by EcutDavid** [comment]
Ah, looks like `JDL` means this repo in JIRA site?

**Comment by michaelneale** [comment]
LGTM

cc @sophistifunk @i386

**Comment by michaelneale** [comment]
yes JDL means this repo. "Jenkins Design Language"

**Comment by michaelneale** [comment]
thank you!

**Pull request merged**
