### PR TITLE
Change table padding to match favourites card and new requirements

### PR DESCRIPTION
**Pull request by sophistifunk**
Does what it says on the box

**Description**
- See [JENKINS-41833](https://issues.jenkins-ci.org/browse/JENKINS-41833).

**Submitter checklist**
- [X] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests

**Reviewer checklist**
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@reviewbybees

### CODE REVIEW

**Comment by sophistifunk** [comment]
screen shot 2017-03-23 at 1 55 11 pm

**Comment by brody** [comment]
Looking good.

Looks like there a few things off.
- Right stars should be inset by 24px.
- Should we expand PR to "Pull Request"?

image

**Comment by sophistifunk** [comment]
@brody 
 - This change is unrelated to the contents of the tables, so no need to address the headers here.
 - Originally it was 24px on the table which can be seen in the diff. When I updated the fav cards I noticed they had 16px so it didn't line up. Last time I checked a few days ago, you said it was 16px ( https://projects.invisionapp.com/share/Q2A110KM9#/screens/217973314_Dashboard_-_Search_1_Redline ). If these things are going to keep changing that's fine, but we need some sort of notice to be posted to the Jira tickets.

**Comment by brody** [comment]
@sophistifunk 
- NP re the header.
- Dang it! The mockups in the Jira ticket and Zeplin were correct. I didn't think to update Invision as it wasn't linked to in the Jira ticket. I forgot that the table and favs are independent of each other, so fixing the inset to 24px is bigger than a table tweak.

**Comment by sophistifunk** [comment]
So we want it 24px for tables (inc border) and for fav cards?

**Comment by brody** [comment]
@sophistifunk That would be perfect. 👍

**Comment by sophistifunk** [comment]
I've added some fixes for an issue with missing children that was giving me guff in the Dashboard actions screen, since I had this PR open already.

**Comment by michaelneale** [comment]
code seems nice, as much as I am qualified... some good fixes in there.

**Comment by michaelneale** [comment]
:bee:

**Pull request merged**
