### PR TITLE
feature/ux 531- button styles

### PR DESCRIPTION
**Pull request by cliffmeyers**
Summary of changes:
* New styles
* Scrabbed default button style that was giving ugly gray buttons. I can't imagine we'd ever want them to look like that, so now default and primary are the same thing.
* Added storybook to illustrate styles

@reviewbybees

### CODE REVIEW

**Comment by cliffmeyers** [comment]
Storybooks:

ux-531-buttons-default

ux-531-buttons-inverse

**Comment by cliffmeyers** [comment]
@i386 added some screenies of the storybooks for your reference / approval.

**Comment by i386** [comment]
LGTM!

**Comment by michaelneale** [comment]
🐝

**Pull request merged**
